name: Sbox

on:
  workflow_dispatch: # Bu satır manuel başlatma butonu ekler

jobs:
  build:
    runs-on: windows-2025 # Visual Studio 2026 desteği için en güncel Windows imajı
    steps:
      - name: Kodu Cek
        uses: actions/checkout@v4

      - name: .NET 10 Kur
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Bağımlılıkları Kur ve Derle
        run: |
          call Bootstrap.bat

      - name: Oyunu Paketle ve İndirme Linki Yap
        uses: actions/upload-artifact@v4
        with:
          name: sbox
          path: game/
